import { Suspense } from "react";
import type { Metadata } from "next";
import { MarketingHeader, MarketingLink } from "@/components/MarketingBack";
import { ScreenHeader } from "@/components/ui/ScreenHeader";

export const metadata: Metadata = {
  title: "Terms · Ethos",
  description: "The deal between you and Ethos, in plain words.",
  openGraph: {
    title: "Terms · Ethos",
    description: "The deal between you and Ethos, in plain words.",
  },
};

/** A heading on the page, and the paragraph under it (marketing-3, -15). */
const HEAD = "section-head mt-8";
const READ = "mt-3 text-read text-stone-800";

/** An inline link: underlined at 40% of its colour, full on hover, so it
    reads as a link in both themes (marketing-17). */
const INLINE_LINK =
  "font-semibold text-terracotta-700 underline decoration-[color-mix(in_srgb,currentColor_40%,transparent)] underline-offset-2 hover:decoration-current";

/** A footer link: a 44px target in the caption's voice (marketing-9). */
const FOOT_LINK =
  "press inline-flex min-h-11 items-center px-3 font-semibold text-stone-500 hover:text-ink";

export default function Terms() {
  return (
    <main className="px-5 pb-[max(2.5rem,env(safe-area-inset-bottom))] pt-7">
      {/* Static for a stranger (back to the landing page); back to
          Settings for somebody who came from there (marketing-3). */}
      <Suspense
        fallback={
          <ScreenHeader title="Terms" back={{ href: "/about", label: "Ethos" }} />
        }
      >
        <MarketingHeader title="Terms" />
      </Suspense>
      <p className="mt-2 text-caption text-stone-400">Last updated 25 August 2026</p>

      <p className="mt-5 text-read text-stone-800">
        Ethos is a daily speaking-practice tool. Using it means agreeing to
        these terms.
      </p>

      <h2 className={HEAD}>What Ethos is</h2>
      <p className={READ}>
        You record short takes, the app measures them and an AI writes
        feedback. The feedback is practice coaching, generated by a model. It
        is not professional, medical or therapeutic advice, and scores are
        practice signals, not credentials.
      </p>

      <h2 className={HEAD}>Your recordings</h2>
      <p className={READ}>
        They&apos;re yours. By recording, you give us permission to process
        and store them for one purpose: scoring your speaking and showing
        your progress back to you, as described in the{" "}
        <MarketingLink href="/privacy" className={INLINE_LINK}>
          privacy policy
        </MarketingLink>
        . Only record yourself, or people who have agreed to be recorded.
      </p>

      <h2 className={HEAD}>Your account</h2>
      <p className={READ}>
        Keep your sign-in to yourself; what happens under it is yours. You
        can delete the account at any time from Settings, which removes your
        data as the privacy policy describes.
      </p>

      <h2 className={HEAD}>Fair use</h2>
      <p className={READ}>
        Scoring costs us real money per recording, so usage limits apply and
        working around them (automation, bulk uploads, probing the API) is
        not allowed. Don&apos;t use Ethos to process content that is illegal
        or that harasses someone.
      </p>

      <h2 className={HEAD}>Money</h2>
      <p className={READ}>
        The core loop is free. Coins are earned by practising and never cost
        money; nothing you could ever buy changes a score, a star or a
        streak. If a paid plan ships, its price and terms will be stated
        where you&apos;d pay, before you pay.
      </p>

      <h2 className={HEAD}>The honest limits</h2>
      <p className={READ}>
        Ethos is provided as-is. We work to keep it accurate and available,
        and we don&apos;t guarantee either; an AI transcript or judgement can
        be wrong. To the extent the law allows, our liability is limited to
        re-supplying the service. Nothing here removes rights the Australian
        Consumer Law gives you.
      </p>

      <h2 className={HEAD}>Changes and contact</h2>
      <p className={READ}>
        If these terms change in a way that matters, the date above changes
        and the app will say so. These terms are governed by Australian law.
        Questions:{" "}
        <a href="mailto:hello@speakethos.com" className={INLINE_LINK}>
          hello@speakethos.com
        </a>
        .
      </p>

      <footer className="mt-12 border-t border-hairline pt-6 text-center text-caption text-stone-400">
        <div className="flex flex-wrap justify-center">
          <MarketingLink href="/privacy" className={FOOT_LINK}>
            Privacy
          </MarketingLink>
          <a href="mailto:hello@speakethos.com" className={FOOT_LINK}>
            hello@speakethos.com
          </a>
        </div>
      </footer>
    </main>
  );
}
