import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms · Ethos",
  description: "The deal between you and Ethos, in plain words.",
  openGraph: {
    title: "Terms · Ethos",
    description: "The deal between you and Ethos, in plain words.",
  },
};

export default function Terms() {
  return (
    <main className="px-5 pb-24 pt-10">
      <Link href="/about" className="text-sm text-stone-500">
        ← ethos
      </Link>
      <h1 className="font-display mt-6 text-[34px] leading-[1.15]">Terms</h1>
      <p className="mt-2 text-[12.5px] text-stone-400">
        Last updated 25 August 2026
      </p>

      <p className="mt-5 text-[15px] leading-relaxed text-stone-600">
        Ethos is a daily speaking-practice tool. Using it means agreeing to
        the terms below; they&apos;re short because the deal is simple.
      </p>

      <h2 className="font-display mt-8 text-[19px]">What Ethos is</h2>
      <p className="mt-2 text-[14px] leading-relaxed text-stone-600">
        A practice gym. You record short takes, the app measures them and an
        AI writes feedback. The feedback is practice coaching, generated by a
        model. It is not professional, medical or therapeutic advice, and
        scores are training signals, not credentials.
      </p>

      <h2 className="font-display mt-8 text-[19px]">Your recordings</h2>
      <p className="mt-2 text-[14px] leading-relaxed text-stone-600">
        They&apos;re yours. By recording, you give us permission to process
        and store them for one purpose: scoring your speaking and showing
        your progress back to you, as described in the{" "}
        <Link href="/privacy" className="font-semibold text-terracotta-700">
          privacy policy
        </Link>
        . Only record yourself, or people who have agreed to be recorded.
      </p>

      <h2 className="font-display mt-8 text-[19px]">Your account</h2>
      <p className="mt-2 text-[14px] leading-relaxed text-stone-600">
        Keep your sign-in to yourself; what happens under it is yours. You
        can delete the account at any time from Settings, which removes your
        data as the privacy policy describes.
      </p>

      <h2 className="font-display mt-8 text-[19px]">Fair use</h2>
      <p className="mt-2 text-[14px] leading-relaxed text-stone-600">
        Scoring costs us real money per recording, so usage limits apply and
        working around them (automation, bulk uploads, probing the API) is
        not allowed. Don&apos;t use Ethos to process content that is illegal
        or that harasses someone.
      </p>

      <h2 className="font-display mt-8 text-[19px]">Money</h2>
      <p className="mt-2 text-[14px] leading-relaxed text-stone-600">
        The core loop is free. Coins are earned by practising and never cost
        money; nothing you could ever buy changes a score, a star or a
        streak. If a paid plan ships, its price and terms will be stated
        where you&apos;d pay, before you pay.
      </p>

      <h2 className="font-display mt-8 text-[19px]">The honest limits</h2>
      <p className="mt-2 text-[14px] leading-relaxed text-stone-600">
        Ethos is provided as-is. We work to keep it accurate and available,
        and we don&apos;t guarantee either; an AI transcript or judgement can
        be wrong. To the extent the law allows, our liability is limited to
        re-supplying the service. Nothing here removes rights the Australian
        Consumer Law gives you.
      </p>

      <h2 className="font-display mt-8 text-[19px]">Changes and contact</h2>
      <p className="mt-2 text-[14px] leading-relaxed text-stone-600">
        If these terms change in a way that matters, the date above changes
        and the app will say so. These terms are governed by Australian law.
        Questions:{" "}
        <a
          href="mailto:hello@speakethos.com"
          className="font-semibold text-terracotta-700"
        >
          hello@speakethos.com
        </a>
        .
      </p>

      <p className="mt-10 text-center text-[12.5px] text-stone-400">
        <Link href="/privacy" className="font-semibold text-stone-500">
          Privacy
        </Link>{" "}
        · <span>hello@speakethos.com</span>
      </p>
    </main>
  );
}
